### PR TITLE
Doye

### PR DESCRIPTION
**Pull request by DoyeDesigns**
I added the frontend project structure

### CODE REVIEW

**Comment by EAZYLINK** [comment]
Please, include all the pages or screens for front end

**Comment by EAZYLINK** [comment]
Great!
One last thing, put all this pages inside a single folder called pages. This is to create a clean folder structure. You can leave the index.html where it is because it's the entry point

**Comment by DoyeDesigns** [comment]
I've added the folder for pages

**Review by EAZYLINK — APPROVED** [review]

**Comment by EAZYLINK** [comment]
Thanks for your prompt response

**Pull request merged**
